### ISSUE TITLE
mirror for mbedtls-2.16.6-gpl.tgz is 404, another required

### ISSUE THREAD

**Issue by zecoxao** [bucanero/ps3libraries#6]
http://downloads.arednmesh.org/sources/mbedtls-2.16.6-gpl.tgz suggested

**Comment by bucanero** [comment]
Another option would be https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/mbedtls-2.16.6.tar.gz , but it would probably need some additional adjustments to the script due to the Github folder structure.
